# Generated by Django 3.1.3 on 2021-11-26 19:27

import builtins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('duration_in_sem', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Major',
                'verbose_name_plural': 'Majors',
            },
        ),
        migrations.CreateModel(
            name='MajorAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('max_points', models.IntegerField()),
                ('points', models.IntegerField(blank=True)),
            ],
            options={
                'verbose_name': 'MajorAssignment',
                'verbose_name_plural': 'MajorAssignments',
            },
        ),
        migrations.CreateModel(
            name='MajorCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapy_ects.major')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='MajorCourseStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ects', models.IntegerField(default=0)),
                ('finished', models.BooleanField(default=False)),
                ('major_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapy_ects.majorassignment')),
                ('major_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapy_ects.majorcourse')),
            ],
            options={
                'verbose_name': 'MajorCourseStat',
                'verbose_name_plural': 'MajorCourseStats',
            },
        ),
        migrations.CreateModel(
            name='MajorStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_ects', models.IntegerField(default=210)),
                ('current_ects', models.IntegerField(default=builtins.sum)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapy_ects.major')),
            ],
            options={
                'verbose_name': 'MajorStat',
                'verbose_name_plural': 'MajorStats',
            },
        ),
        migrations.CreateModel(
            name='MajorTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('max_points', models.IntegerField()),
                ('points', models.IntegerField(blank=True)),
            ],
            options={
                'verbose_name': 'MajorTest',
                'verbose_name_plural': 'MajorTests',
            },
        ),
        migrations.CreateModel(
            name='SpecAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('max_points', models.IntegerField()),
                ('points', models.IntegerField(blank=True)),
            ],
            options={
                'verbose_name': 'SpecAssignment',
                'verbose_name_plural': 'SpecAssignments',
            },
        ),
        migrations.CreateModel(
            name='SpecCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'SpecCourse',
                'verbose_name_plural': 'SpecCourses',
            },
        ),
        migrations.CreateModel(
            name='SpecCourseStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ects', models.IntegerField(default=0)),
                ('finished', models.BooleanField(default=False)),
                ('spec_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scrapy_ects.specassignment')),
                ('spec_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapy_ects.speccourse')),
            ],
            options={
                'verbose_name': 'SpecCourseStat',
                'verbose_name_plural': 'SpecCourseStats',
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapy_ects.major')),
            ],
            options={
                'verbose_name': 'Specialization',
                'verbose_name_plural': 'Specializations',
            },
        ),
        migrations.CreateModel(
            name='SpecStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapy_ects.specialization')),
            ],
            options={
                'verbose_name': 'SpecStat',
                'verbose_name_plural': 'SpecStats',
            },
        ),
        migrations.CreateModel(
            name='SpecTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('max_points', models.IntegerField()),
                ('points', models.IntegerField(blank=True)),
            ],
            options={
                'verbose_name': 'SpecTest',
                'verbose_name_plural': 'SpecTests',
            },
        ),
        migrations.CreateModel(
            name='Titles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'title',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_sem', models.IntegerField()),
                ('album_nr', models.IntegerField()),
                ('start_of_major', models.DateField()),
                ('major', models.ManyToManyField(through='scrapy_ects.MajorStat', to='scrapy_ects.Major')),
                ('major_assignment', models.ManyToManyField(blank=True, null=True, through='scrapy_ects.MajorCourseStat', to='scrapy_ects.MajorAssignment')),
                ('major_course', models.ManyToManyField(through='scrapy_ects.MajorCourseStat', to='scrapy_ects.MajorCourse')),
                ('major_test', models.ManyToManyField(blank=True, null=True, through='scrapy_ects.MajorCourseStat', to='scrapy_ects.MajorTest')),
                ('spec_assignment', models.ManyToManyField(blank=True, null=True, through='scrapy_ects.SpecCourseStat', to='scrapy_ects.SpecAssignment')),
                ('spec_course', models.ManyToManyField(through='scrapy_ects.SpecCourseStat', to='scrapy_ects.SpecCourse')),
                ('spec_stat', models.ManyToManyField(through='scrapy_ects.SpecStat', to='scrapy_ects.Specialization')),
                ('spec_test', models.ManyToManyField(blank=True, null=True, through='scrapy_ects.SpecCourseStat', to='scrapy_ects.SpecTest')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.AddField(
            model_name='specstat',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapy_ects.student'),
        ),
        migrations.AddField(
            model_name='speccoursestat',
            name='spec_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scrapy_ects.spectest'),
        ),
        migrations.AddField(
            model_name='speccoursestat',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapy_ects.student'),
        ),
        migrations.AddField(
            model_name='speccourse',
            name='spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapy_ects.specialization'),
        ),
        migrations.AddField(
            model_name='majorstat',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapy_ects.student'),
        ),
        migrations.AddField(
            model_name='majorcoursestat',
            name='major_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapy_ects.majortest'),
        ),
        migrations.AddField(
            model_name='majorcoursestat',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapy_ects.student'),
        ),
    ]
