# Generated by Django 3.2.5 on 2021-11-29 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy_ects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='majorcoursestat',
            name='major_assignment',
        ),
        migrations.RemoveField(
            model_name='majorcoursestat',
            name='major_test',
        ),
        migrations.RemoveField(
            model_name='speccoursestat',
            name='spec_assignment',
        ),
        migrations.RemoveField(
            model_name='speccoursestat',
            name='spec_test',
        ),
        migrations.RemoveField(
            model_name='student',
            name='major_assignment',
        ),
        migrations.RemoveField(
            model_name='student',
            name='major_test',
        ),
        migrations.RemoveField(
            model_name='student',
            name='spec_assignment',
        ),
        migrations.RemoveField(
            model_name='student',
            name='spec_test',
        ),
        migrations.AddField(
            model_name='majorassignment',
            name='major',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrapy_ects.majorcoursestat'),
        ),
        migrations.AddField(
            model_name='majortest',
            name='major',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrapy_ects.majorcoursestat'),
        ),
        migrations.AddField(
            model_name='specassignment',
            name='spec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrapy_ects.speccoursestat'),
        ),
        migrations.AddField(
            model_name='spectest',
            name='spec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrapy_ects.speccoursestat'),
        ),
    ]
