# Generated by Django 3.2.5 on 2021-12-02 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy_ects', '0003_alter_student_spec_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Titles',
        ),
        migrations.RemoveField(
            model_name='student',
            name='start_of_major',
        ),
        migrations.AddField(
            model_name='major',
            name='department',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='majorcoursestat',
            name='course_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='majorcoursestat',
            name='degree',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='majorstat',
            name='start_of_major',
            field=models.DateField(default=datetime.date(2021, 12, 2)),
        ),
        migrations.AlterField(
            model_name='majorcoursestat',
            name='ects',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_sem',
            field=models.IntegerField(blank=True),
        ),
    ]
