# Generated by Django 3.2.5 on 2021-12-02 10:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy_ects', '0004_auto_20211202_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majorstat',
            name='start_of_major',
            field=models.DateField(default=datetime.datetime(2021, 12, 2, 10, 39, 47, 22779, tzinfo=utc)),
        ),
    ]
