# Generated by Django 3.2.5 on 2021-12-02 10:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy_ects', '0005_alter_majorstat_start_of_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majorstat',
            name='start_of_major',
            field=models.DateField(default=datetime.datetime(2021, 12, 2, 10, 41, 25, 163641, tzinfo=utc)),
        ),
    ]
