# Generated by Django 3.2.5 on 2021-12-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy_ects', '0006_alter_majorstat_start_of_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majorstat',
            name='start_of_major',
            field=models.DateField(auto_now=True),
        ),
    ]
