# Generated by Django 3.2.5 on 2021-12-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy_ects', '0007_alter_majorstat_start_of_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majorstat',
            name='current_ects',
            field=models.IntegerField(),
        ),
    ]
