# Generated by Django 3.2.5 on 2021-12-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy_ects', '0008_alter_majorstat_current_ects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='department',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_sem',
            field=models.IntegerField(),
        ),
    ]
