# Generated by Django 3.2.5 on 2021-12-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy_ects', '0010_auto_20211202_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_sem',
            field=models.IntegerField(blank=True),
        ),
    ]
