# Generated by Django 3.2.5 on 2021-12-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy_ects', '0013_alter_student_album_nr'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='major',
            constraint=models.UniqueConstraint(fields=('name', 'duration_in_sem'), name='unique_major'),
        ),
    ]
