# Generated by Django 3.2.5 on 2021-12-02 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy_ects', '0015_alter_major_duration_in_sem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majorstat',
            name='current_ects',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
