# Generated by Django 3.2.5 on 2021-12-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy_ects', '0017_alter_majorstat_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='majorcourse',
            options={'verbose_name': 'MajorCourse', 'verbose_name_plural': 'MajorCourses'},
        ),
        migrations.AddConstraint(
            model_name='majorcourse',
            constraint=models.UniqueConstraint(fields=('name', 'major'), name='unique_major_course'),
        ),
    ]
