# Generated by Django 3.2.5 on 2021-12-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy_ects', '0018_auto_20211203_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speccoursestat',
            old_name='finished',
            new_name='course_passed',
        ),
        migrations.RemoveField(
            model_name='majorcoursestat',
            name='finished',
        ),
        migrations.AddField(
            model_name='speccoursestat',
            name='degree',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='majorcoursestat',
            name='ects',
            field=models.IntegerField(default=0),
        ),
    ]
