# Generated by Django 3.2.5 on 2021-12-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy_ects', '0021_rename_spec_stat_student_spec'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='spec',
            constraint=models.UniqueConstraint(fields=('name', 'major'), name='unique_spec'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('album_nr',), name='unique_student'),
        ),
    ]
