# Generated by Django 3.2.5 on 2021-12-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy_ects', '0023_auto_20211204_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='majorcoursestat',
            name='lecturer',
            field=models.CharField(default='x', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='majorcoursestat',
            name='semester',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='majorcoursestat',
            name='sylabus',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='majorcoursestat',
            name='total_points',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='majorcoursestat',
            name='total_points_scored',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speccoursestat',
            name='lecturer',
            field=models.CharField(default='x', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speccoursestat',
            name='semester',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speccoursestat',
            name='sylabus',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='speccoursestat',
            name='total_points',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speccoursestat',
            name='total_points_scored',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
