# Generated by Django 3.2.5 on 2021-12-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy_ects', '0024_auto_20211205_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majorcoursestat',
            name='total_points',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='speccoursestat',
            name='total_points',
            field=models.IntegerField(default=100),
        ),
    ]
