# Generated by Django 3.2.5 on 2021-12-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy_ects', '0025_auto_20211208_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majorcoursestat',
            name='total_points_scored',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speccoursestat',
            name='total_points_scored',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
