# Generated by Django 3.2.5 on 2021-12-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy_ects', '0026_auto_20211209_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majorcoursestat',
            name='lecturer',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='speccoursestat',
            name='lecturer',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
