# Generated by Django 3.2.5 on 2022-01-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy_ects', '0030_auto_20220114_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majorassignment',
            name='has_date',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='specassignment',
            name='has_date',
            field=models.BooleanField(),
        ),
    ]
