# Generated by Django 3.2.5 on 2022-01-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy_ects', '0031_auto_20220114_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majorassignment',
            name='points',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='specassignment',
            name='points',
            field=models.FloatField(default=0),
        ),
    ]
