# Generated by Django 3.2.5 on 2022-01-14 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy_ects', '0033_auto_20220114_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majorassignment',
            name='the_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='specassignment',
            name='the_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
