# Generated by Django 3.2.5 on 2022-02-08 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy_ects', '0034_auto_20220114_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='majortest',
            name='has_date',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='majortest',
            name='the_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spectest',
            name='has_date',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spectest',
            name='the_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='majortest',
            name='max_points',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='majortest',
            name='more_info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='majortest',
            name='points',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='spectest',
            name='max_points',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='spectest',
            name='more_info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='spectest',
            name='points',
            field=models.FloatField(default=0),
        ),
        migrations.AddConstraint(
            model_name='majorassignment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('has_date__exact', True), ('the_date__isnull', False)), models.Q(('has_date__exact', False), ('the_date__isnull', True)), _connector='OR'), name='the_major_date_check'),
        ),
        migrations.AddConstraint(
            model_name='specassignment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('has_date', True), ('the_date__isnull', False)), models.Q(('has_date', False), ('the_date__isnull', True)), _connector='OR'), name='the_spec_date_check'),
        ),
    ]
