# Generated by Django 3.2.5 on 2022-02-08 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy_ects', '0035_auto_20220208_0401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='majorassignment',
            old_name='major_course_stat',
            new_name='course_stat',
        ),
        migrations.RenameField(
            model_name='majortest',
            old_name='major_course_stat',
            new_name='course_stat',
        ),
        migrations.RenameField(
            model_name='specassignment',
            old_name='spec_course_stat',
            new_name='course_stat',
        ),
        migrations.RenameField(
            model_name='spectest',
            old_name='spec_course_stat',
            new_name='course_stat',
        ),
    ]
